"""app/routes/digital_download_routes.py

Secure signed download endpoint for digital products.

GET /api/v1/download/{token}
  - Validates HMAC-SHA256 token generated by digital_fulfillment_service
  - Returns 401 on invalid signature
  - Returns 410 Gone on expired token
  - Returns 302 Redirect to canonical Cloudflare R2 asset URL on success

Token format: `{base64url_payload}.{hex_sha256_signature}`
Secret: DOWNLOAD_SECRET_KEY environment variable

Registered in both FastAPI and aiohttp runners per ARCHITECTURE.md §1.
"""

import logging

from aiohttp import web
from fastapi import APIRouter
from fastapi.responses import RedirectResponse, JSONResponse

from app.services.digital_fulfillment_service import verify_download_token

logger = logging.getLogger("DIGITAL_DOWNLOAD")

router = APIRouter(prefix="/api/v1", tags=["Digital Downloads"])


# ---------------------------------------------------------------------------
# FastAPI handler
# ---------------------------------------------------------------------------

@router.get("/download/{token}", summary="Secure Signed Digital Product Download")
async def handle_digital_download(token: str):
    """
    Validates a signed download token and redirects to the product file URL.

    - 302 Redirect → Cloudflare R2 canonical URL on success
    - 401 Unauthorized → invalid signature
    - 410 Gone → token expired
    """
    try:
        payload = verify_download_token(token)
    except ValueError as exc:
        logger.warning(f"[DigitalDownload] Invalid token: {exc}")
        return JSONResponse(
            status_code=401,
            content={"error": "Invalid or tampered download token.", "detail": str(exc)},
        )
    except PermissionError as exc:
        logger.warning(f"[DigitalDownload] Expired token: {exc}")
        return JSONResponse(
            status_code=410,
            content={"error": "Download link has expired. Please request a new link.", "detail": str(exc)},
        )
    except Exception as exc:
        logger.error(f"[DigitalDownload] Unexpected token error: {exc}", exc_info=True)
        return JSONResponse(status_code=500, content={"error": "Internal server error."})

    file_url: str = payload.get("file_url", "")
    if not file_url:
        return JSONResponse(status_code=404, content={"error": "File not found in token payload."})

    logger.info(
        f"[DigitalDownload] Valid download: product={payload.get('product_id')} "
        f"buyer={payload.get('buyer_email')}"
    )
    return RedirectResponse(url=file_url, status_code=302)


# ---------------------------------------------------------------------------
# aiohttp handler (dual-runner compliance — ARCHITECTURE.md §1)
# ---------------------------------------------------------------------------

async def aiohttp_digital_download(request: web.Request) -> web.Response:
    token = request.match_info.get("token", "")

    try:
        payload = verify_download_token(token)
    except ValueError as exc:
        return web.json_response(
            {"error": "Invalid or tampered download token.", "detail": str(exc)},
            status=401,
        )
    except PermissionError as exc:
        return web.json_response(
            {"error": "Download link has expired. Please request a new link.", "detail": str(exc)},
            status=410,
        )
    except Exception as exc:
        logger.error(f"[DigitalDownload][aiohttp] Unexpected error: {exc}", exc_info=True)
        return web.json_response({"error": "Internal server error."}, status=500)

    file_url: str = payload.get("file_url", "")
    if not file_url:
        return web.json_response({"error": "File not found in token payload."}, status=404)

    logger.info(
        f"[DigitalDownload][aiohttp] Valid download: product={payload.get('product_id')} "
        f"buyer={payload.get('buyer_email')}"
    )
    raise web.HTTPFound(location=file_url)


def register_digital_download_routes(aiohttp_app: web.Application) -> None:
    """Register aiohttp download route (dual-runner)."""
    aiohttp_app.router.add_get("/api/v1/download/{token}", aiohttp_digital_download)
    logger.info("[DigitalDownload] aiohttp routes registered.")
