# Template Statis & Data Kritis (LLM Dilarang Memproduksi String Ini)
REKENING_OM_BUDI = (
    "PROGRAM SEDEKAH BERJAMAAH & ORANG TUA ASUH\n"
    "Bersama Om Budi Channel\n\n"
    "Bapak Ibu yang dirahmati Allah,\n\n"
    "Mari bersama-sama mendukung keberlangsungan dakwah, majelis ilmu, dan berbagai program kebaikan melalui Program Zoom Booster.\n\n"
    "Sesuai kesepakatan bersama, kontribusi program ini dimulai dari Rp50.000 atau lebih setiap bulan sesuai kemampuan masing-masing.\n\n"
    "💳 *Rekening Penyaluran:*\n"
    "Bank Syariah Indonesia (BSI)\n"
    "a.n. Budi Yulianto\n"
    "• Program Zoom Booster : *7251759094*\n"
    "• Program Orang Tua Asuh : *7262970951*\n\n"
    "💳 *Bank Mandiri:*\n"
    "a.n. Budi Yulianto\n"
    "• Program Zoom Booster : *1320022006077*\n\n"
    "📲 *Konfirmasi Transfer:*\n"
    "Setelah transfer, mohon kirim bukti transfer ke nomor admin ini ya 😊🙏."
)

ZOOM_INFO_OM_BUDI = (
    "🔗 *Link & Cara Masuk Zoom Booster*\n\n"
    "• Jadwal: Setiap **Rabu malam** pukul **20.00 WIB**\n"
    "• Link Pertemuan: *https://zoom.us/j/boontrack-ombudi*\n"
    "• Passcode: *SHOLAWAT*\n\n"
    "_Buka tautan di atas saat jam acara dimulai ya Bapak/Ibu 😊🙏._"
)

AUDIO_BRAINWAVE_OM_BUDI = (
    "🎧 *PANDUAN & LINK DOWNLOAD AUDIO BRAINWAVE QUANTUM ENERGI* 🤲\n\n"
    "Bismillah, berikut tautan resmi download/streaming 3 Audio Bimbingan Om Budi:\n\n"
    "1️⃣ *Digital Prayers Quantum Ikhlas (Utama)*:\n"
    "👉 https://drive.google.com/file/d/18GjQd8SMymV8kxfvOPodvIXNxlVLbhW9/view?usp=drivesdk\n\n"
    "2️⃣ *Meditasi Syukur (Kekayaan & Kesehatan)*:\n"
    "👉 https://drive.google.com/file/d/1yw1fVPT6mpPiqj27P0qu_yiNfrTKv4tr/view?usp=drive_link\n\n"
    "3️⃣ *Audio Terapi Menarik Rezeki*:\n"
    "👉 https://drive.google.com/file/d/1zJOXiu-A-Jlh713tIvULS-tfbBBUEKLp/view?usp=drive_link\n\n"
    "━━━━━━━━━━━━━━━━━━\n"
    "📌 *Petunjuk Penggunaan:*\n"
    "• Dengarkan 2x sehari (pagi setelah Subuh/Dhuha dan malam sebelum tidur).\n"
    "• Gunakan *earphone/headphone* dengan volume sedang yang nyaman.\n"
    "• Duduk relaks atau berbaring di ruangan yang tenang (20–60 menit).\n"
    "• Praktikkan 4 langkah: *Alphamatic -> Niat Hajat -> Visualisasi Syukur -> Pasrah (Alhamdulillah)*.\n\n"
    "⚠️ *PANTANGAN PENTING*:\n"
    "❌ Dilarang mendengarkan saat menyetir kendaraan atau mengoperasikan mesin!\n"
    "❌ Tidak diperkenankan untuk penderita epilepsi atau pengguna alat pacu jantung.\n\n"
    "Semoga vibrasi doa dan riyadhoh Bapak/Ibu semakin selaras, tenang, dan diijabah Allah SWT 🤲🙏."
)

MATERI_RIYADHOH_OM_BUDI = (
    "📚 *PANDUAN & MATERI RIYADHOH SHOLAWAT OM BUDI* 🤲\n\n"
    "Bismillah, berikut ringkasan panduan Riyadhoh Jalur Langit 40 Hari:\n\n"
    "1️⃣ *Sholat Wajib 5 Waktu*: Tepat waktu & berjamaah.\n"
    "2️⃣ *Sholat Dhuha*: Minimal 4 rakaat (2 rakaat 1 salam).\n"
    "3️⃣ *Qiyamul Lail (Sepertiga Malam)*:\n"
    "   • Sholat Taubat 2 rakaat\n"
    "   • Sholat Tahajud minimal 4 rakaat\n"
    "   • Sholat Hajat 2 rakaat & Sholat Witir 3 rakaat\n"
    "   • Istighfar setelah Witir: _'Robbighfirli wa tub 'alayya innaka antat tawwabur rohim'_\n"
    "4️⃣ *Sedekah Subuh*: Rutin setiap pagi diiringi doa hajat.\n"
    "5️⃣ *Sholawat Jibril*: Minimal 1.000x setiap hari (_'Shallallahu 'ala Muhammad'_).\n"
    "6️⃣ *Asmaul Husna*: Baca 33x setelah Subuh (_'Ya Hannan Ya Mannan, Ya Fattah Ya Rozzaq, Ya Ghoniy Ya Mughni'_).\n"
    "7️⃣ *Audio Brainwave*: Dengarkan audio bimbingan relaksasi & visualisasi syukur.\n\n"
    "🔗 *Akses Audio Bimbingan:*\n"
    "• Digital Prayers Quantum Ikhlas: https://drive.google.com/file/d/18GjQd8SMymV8kxfvOPodvIXNxlVLbhW9/view?usp=drivesdk\n"
    "• Meditasi Syukur: https://drive.google.com/file/d/1yw1fVPT6mpPiqj27P0qu_yiNfrTKv4tr/view?usp=drive_link\n"
    "• Terapi Rezeki: https://drive.google.com/file/d/1zJOXiu-A-Jlh713tIvULS-tfbBBUEKLp/view?usp=drive_link\n\n"
    "Semoga istiqomah dan Allah karuniakan jalan keluar terbaik untuk segala amanah 🤲😊."
)